### ISSUE TITLE
Checklist for guppy 0.1.0

### ISSUE THREAD

**Issue by sunshowers** [calibra/cargo-guppy#35]
- [x] finish up docs
- [x] re-export any exports we use (e.g. `cargo_metadata::PackageId`, `cargo_metadata::Metadata`, `cargo_metadata::MetadataCommand`, `serde_json::Value` etc)
- [x] inspect `cargo publish --dry-run` and ensure it looks good
- [x] tag release
- [x] publish!
